#include "simple_graph/tree/tree.hpp"
#include "simple_graph/random_DAG/random_DAG.hpp"
#include "simple_graph/extreme_graph/parallel_graph.hpp"
#include "simple_graph/extreme_graph/serial_graph.hpp"
#include "simple_graph/map_reduce/diamond.hpp"
